version: '3'
services:
  rgbasm:
    build: . 
    command: 'rgbasm -o obj/hellowindow.o hellowindow.asm' 
    volumes: 
    - .:/app
  rgblink:
    build: . 
    depends_on: 
    - rgbasm
    command: 'rgblink -o bin/hellowindow.gb obj/hellowindow.o' 
    volumes: 
    - .:/app
  rgbfix:
    build: . 
    depends_on: 
    - rgblink
    command: 'rgbfix -v -p 0 bin/hellowindow.gb' 
    volumes: 
    - .:/app