version: '3'
services:
  rgbasm:
    build: . 
    command: 'rgbasm -o obj/main.o main.asm' 
    volumes: 
    - .:/app
  rgblink:
    build: . 
    depends_on: 
    - rgbasm
    command: 'rgblink -o bin/hello-world.gb obj/main.o' 
    volumes: 
    - .:/app
  rgbfix:
    build: . 
    depends_on: 
    - rgblink
    command: 'rgbfix -v -p 0 bin/hello-world.gb' 
    volumes: 
    - .:/app